# Generated by Django 5.2.7 on 2025-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('visitor', 'Visitor'), ('recruiter', 'Recruiter'), ('contributor', 'Contributor')], default='visitor', help_text='Select one: Admin, Visitor, Recruiter, or Contributor', max_length=15),
        ),
    ]
